"""
Streamlit dashboard layer for the Sales Analytics project.

Consumes precomputed outputs generated by the analysis pipeline (src.main):
- reports/sales_by_quarter.csv
- reports/sales_by_month.csv
- reports/insights.md

Goal: provide an executive-friendly, interactive view of key trends and insights.
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path

# App configuration (wide layout to match typical BI dashboard viewing)
st.set_page_config(page_title="Sales Dashboard", layout="wide")

# Styling layer: enforce clean red/white/black theme + center the Executive Insights section
# (Streamlit markdown tables don't always render with strong borders by default.)
st.markdown("""
<style>
  .insights-wrapper{
    max-width: 900px;
    margin: 0 auto;
  }

  .insights-card {
    border: 1px solid #e9e9e9;
    border-left: 6px solid #c1121f;
    border-radius: 16px;
    padding: 18px 18px 10px 18px;
    background: #ffffff;
    box-shadow: 0 1px 6px rgba(0,0,0,0.04);
  }

  .insights-card h1, .insights-card h2, .insights-card h3, .insights-card h4 {
    text-align: center !important;
    margin-top: 10px;
  }

  .insights-card ul {
    display: inline-block;
    text-align: left;
    margin: 0 auto 12px auto;
    padding-left: 22px;
  }

  .insights-card table {
    width: 100%;
    margin: 10px auto 18px auto !important;
    border-collapse: separate;
    border-spacing: 0;
    border: 1px solid #e5e5e5;
    border-radius: 12px;
    overflow: hidden;
    background: #ffffff;
  }

  .insights-card thead th {
    background: #111111;
    color: #ffffff;
    font-weight: 800;
    text-align: center !important;
    padding: 10px 12px;
    border-bottom: 1px solid #2a2a2a;
  }

  .insights-card tbody td {
    text-align: center !important;
    padding: 10px 12px;
    border-bottom: 1px solid #efefef;
    border-right: 1px solid #f2f2f2;
  }

  .insights-card tbody td:last-child {
    border-right: none;
  }

  .insights-card tbody tr:nth-child(even) td {
    background: #fafafa;
  }

  .insights-card tbody tr:last-child td {
    border-bottom: none;
  }
</style>
""", unsafe_allow_html=True)

# Title / branding
st.markdown('<div class="main-title">Sales Analytics Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Red • White • Black — clean executive view</div>', unsafe_allow_html=True)

# Load pipeline outputs (generated by: python -m src.main)
REPORTS_DIR = Path(__file__).resolve().parents[1] / "reports"
sales_quarter = pd.read_csv(REPORTS_DIR / "sales_by_quarter.csv")
sales_month = pd.read_csv(REPORTS_DIR / "sales_by_month.csv")

# Executive KPIs (quick snapshot). Growth compares last quarter vs previous quarter.
total_sales = float(sales_month["sales"].sum())
latest_quarter_sales = float(sales_quarter.iloc[-1]["sales"])
previous_quarter_sales = float(sales_quarter.iloc[-2]["sales"])
growth_pct = ((latest_quarter_sales - previous_quarter_sales) / previous_quarter_sales) * 100 if previous_quarter_sales != 0 else 0.0

st.markdown('<div class="section-title">Key Metrics</div>', unsafe_allow_html=True)
c1, c2, c3 = st.columns(3)
with c1:
    st.metric("Total Sales", f"${total_sales:,.0f}")
with c2:
    st.metric("Latest Quarter Sales", f"${latest_quarter_sales:,.0f}")
with c3:
    st.metric("Quarter Growth", f"{growth_pct:.2f}%")

# Quarterly chart
st.markdown('<div class="section-title">Quarterly Sales</div>', unsafe_allow_html=True)
st.markdown('<div class="chart-card">', unsafe_allow_html=True)

fig_q = px.bar(sales_quarter, x="year_quarter", y="sales")
fig_q.update_layout(
    plot_bgcolor="#ffffff",
    paper_bgcolor="#ffffff",
    font=dict(color="#111111"),
    xaxis=dict(title="Quarter", showgrid=False),
    yaxis=dict(title="Sales", gridcolor="#efefef"),
    margin=dict(l=10, r=10, t=10, b=10),
)
fig_q.update_traces(marker_color="#c1121f")
st.plotly_chart(fig_q, use_container_width=True)
st.markdown("</div>", unsafe_allow_html=True)

# Monthly trend chart
st.markdown('<div class="section-title">Monthly Trend</div>', unsafe_allow_html=True)
st.markdown('<div class="chart-card">', unsafe_allow_html=True)

fig_m = px.line(sales_month, x="year_month", y="sales", markers=True)
fig_m.update_layout(
    plot_bgcolor="#ffffff",
    paper_bgcolor="#ffffff",
    font=dict(color="#111111"),
    xaxis=dict(title="Month", showgrid=False),
    yaxis=dict(title="Sales", gridcolor="#efefef"),
    margin=dict(l=10, r=10, t=10, b=10),
)
fig_m.update_traces(line_color="#111111", marker=dict(color="#c1121f", size=7))
st.plotly_chart(fig_m, use_container_width=True)
st.markdown("</div>", unsafe_allow_html=True)

# Render executive markdown produced by the pipeline (includes tables of key drivers)
st.markdown('<div class="section-title">Executive Insights</div>', unsafe_allow_html=True)
st.markdown('<div class="insights-wrapper"><div class="insights-card">', unsafe_allow_html=True)

insights_path = REPORTS_DIR / "insights.md"
with open(insights_path, "r", encoding="utf-8") as f:
    st.markdown(f.read())

st.markdown("</div></div>", unsafe_allow_html=True)